##### The goal of this notebook is to scrape **Tafseer Al-Jalalayn** from the website

`https://www.altafsir.com`

The link of the website for each Ayah follows this format

`https://www.altafsir.com/Tafasir.asp?tMadhNo=0&tTafsirNo=74&tSoraNo={Surrah_Number}&tAyahNo={Ayah_Number}&tDisplay=yes&UserProfile=0&LanguageId=2`

In [3]:
pip install selenium

Collecting selenium
  Downloading selenium-4.39.0-py3-none-any.whl.metadata (7.5 kB)
Requirement already satisfied: urllib3<3.0,>=2.5.0 in c:\users\loq\documents\github\rag\.venv\lib\site-packages (from urllib3[socks]<3.0,>=2.5.0->selenium) (2.6.2)
Collecting trio<1.0,>=0.31.0 (from selenium)
  Downloading trio-0.32.0-py3-none-any.whl.metadata (8.5 kB)
Collecting trio-websocket<1.0,>=0.12.2 (from selenium)
  Downloading trio_websocket-0.12.2-py3-none-any.whl.metadata (5.1 kB)
Requirement already satisfied: certifi>=2025.10.5 in c:\users\loq\documents\github\rag\.venv\lib\site-packages (from selenium) (2025.11.12)
Requirement already satisfied: typing_extensions<5.0,>=4.15.0 in c:\users\loq\documents\github\rag\.venv\lib\site-packages (from selenium) (4.15.0)
Requirement already satisfied: websocket-client<2.0,>=1.8.0 in c:\users\loq\documents\github\rag\.venv\lib\site-packages (from selenium) (1.9.0)
Requirement already satisfied: attrs>=23.2.0 in c:\users\loq\documents\github\rag\.venv\lib\site-packages (from trio<1.0,>=0.31.0->selenium) (25.4.0)
Collecting sortedcontainers (from trio<1.0,>=0.31.0->selenium)
  Downloading sortedcontainers-2.4.0-py2.py3-none-any.whl.metadata (10 kB)
Requirement already satisfied: idna in c:\users\loq\documents\github\rag\.venv\lib\site-packages (from trio<1.0,>=0.31.0->selenium) (3.11)
Collecting outcome (from trio<1.0,>=0.31.0->selenium)
  Downloading outcome-1.3.0.post0-py2.py3-none-any.whl.metadata (2.6 kB)
Collecting sniffio>=1.3.0 (from trio<1.0,>=0.31.0->selenium)
  Downloading sniffio-1.3.1-py3-none-any.whl.metadata (3.9 kB)
Requirement already satisfied: cffi>=1.14 in c:\users\loq\documents\github\rag\.venv\lib\site-packages (from trio<1.0,>=0.31.0->selenium) (2.0.0)
Collecting wsproto>=0.14 (from trio-websocket<1.0,>=0.12.2->selenium)
  Downloading wsproto-1.3.2-py3-none-any.whl.metadata (5.2 kB)
Collecting pysocks!=1.5.7,<2.0,>=1.5.6 (from urllib3[socks]<3.0,>=2.5.0->selenium)
  Downloading PySocks-1.7.1-py3-none-any.whl.metadata (13 kB)
Requirement already satisfied: pycparser in c:\users\loq\documents\github\rag\.venv\lib\site-packages (from cffi>=1.14->trio<1.0,>=0.31.0->selenium) (2.23)
Requirement already satisfied: h11<1,>=0.16.0 in c:\users\loq\documents\github\rag\.venv\lib\site-packages (from wsproto>=0.14->trio-websocket<1.0,>=0.12.2->selenium) (0.16.0)
Downloading selenium-4.39.0-py3-none-any.whl (9.7 MB)
   ---------------------------------------- 0.0/9.7 MB ? eta -:--:--
   - -------------------------------------- 0.3/9.7 MB ? eta -:--:--
   ---- ----------------------------------- 1.0/9.7 MB 3.6 MB/s eta 0:00:03
   ------- -------------------------------- 1.8/9.7 MB 3.7 MB/s eta 0:00:03
   ---------- ----------------------------- 2.6/9.7 MB 3.8 MB/s eta 0:00:02
   -------------- ------------------------- 3.4/9.7 MB 3.8 MB/s eta 0:00:02
   ----------------- ---------------------- 4.2/9.7 MB 3.9 MB/s eta 0:00:02
   -------------------- ------------------- 5.0/9.7 MB 3.9 MB/s eta 0:00:02
   --------------------- ------------------ 5.2/9.7 MB 3.5 MB/s eta 0:00:02
   --------------------- ------------------ 5.2/9.7 MB 3.5 MB/s eta 0:00:02
   --------------------- ------------------ 5.2/9.7 MB 3.5 MB/s eta 0:00:02
   ---------------------- ----------------- 5.5/9.7 MB 2.6 MB/s eta 0:00:02
   ---------------------- ----------------- 5.5/9.7 MB 2.6 MB/s eta 0:00:02
   ---------------------- ----------------- 5.5/9.7 MB 2.6 MB/s eta 0:00:02
   -------------------------- ------------- 6.3/9.7 MB 2.3 MB/s eta 0:00:02
   -------------------------- ------------- 6.3/9.7 MB 2.3 MB/s eta 0:00:02
   --------------------------- ------------ 6.6/9.7 MB 2.1 MB/s eta 0:00:02
   --------------------------- ------------ 6.6/9.7 MB 2.1 MB/s eta 0:00:02
   ----------------------------- ---------- 7.1/9.7 MB 1.9 MB/s eta 0:00:02
   -------------------------------- ------- 7.9/9.7 MB 2.1 MB/s eta 0:00:01
   ----------------------------------- ---- 8.7/9.7 MB 2.1 MB/s eta 0:00:01
   -------------------------------------- - 9.2/9.7 MB 2.1 MB/s eta 0:00:01
   ---------------------------------------- 9.7/9.7 MB 2.1 MB/s eta 0:00:00
Downloading trio-0.32.0-py3-none-any.whl (512 kB)
Downloading trio_websocket-0.12.2-py3-none-any.whl (21 kB)
Downloading PySocks-1.7.1-py3-none-any.whl (16 kB)
Downloading outcome-1.3.0.post0-py2.py3-none-any.whl (10 kB)
Downloading sniffio-1.3.1-py3-none-any.whl (10 kB)
Downloading wsproto-1.3.2-py3-none-any.whl (24 kB)
Downloading sortedcontainers-2.4.0-py2.py3-none-any.whl (29 kB)
Installing collected packages: sortedcontainers, wsproto, sniffio, pysocks, outcome, trio, trio-websocket, selenium

   ---------- ----------------------------- 2/8 [sniffio]
   ------------------------- -------------- 5/8 [trio]
   ------------------------- -------------- 5/8 [trio]
   ------------------------- -------------- 5/8 [trio]
   ------------------------- -------------- 5/8 [trio]
   ------------------------- -------------- 5/8 [trio]
   ------------------------- -------------- 5/8 [trio]
   ------------------------- -------------- 5/8 [trio]
   ----------------------------------- ---- 7/8 [selenium]
   ----------------------------------- ---- 7/8 [selenium]
   ----------------------------------- ---- 7/8 [selenium]
   ----------------------------------- ---- 7/8 [selenium]
   ----------------------------------- ---- 7/8 [selenium]
   ----------------------------------- ---- 7/8 [selenium]
   ----------------------------------- ---- 7/8 [selenium]
   ----------------------------------- ---- 7/8 [selenium]
   ----------------------------------- ---- 7/8 [selenium]
   ----------------------------------- ---- 7/8 [selenium]
   ----------------------------------- ---- 7/8 [selenium]
   ----------------------------------- ---- 7/8 [selenium]
   ----------------------------------- ---- 7/8 [selenium]
   ----------------------------------- ---- 7/8 [selenium]
   ----------------------------------- ---- 7/8 [selenium]
   ----------------------------------- ---- 7/8 [selenium]
   ---------------------------------------- 8/8 [selenium]

Successfully installed outcome-1.3.0.post0 pysocks-1.7.1 selenium-4.39.0 sniffio-1.3.1 sortedcontainers-2.4.0 trio-0.32.0 trio-websocket-0.12.2 wsproto-1.3.2
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.1.1 -> 25.3
[notice] To update, run: python.exe -m pip install --upgrade pip

In [5]:
import pandas as pd
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.chrome.options import Options
from tqdm import tqdm
import time
import os
import json
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC

In [3]:
quran = pd.read_csv("Datasets\quran_surahs.csv")
quran

     Surah Number  Surah Name  Number of Ayat
0               1   Al-Fatiha               7
1               2  Al-Baqarah             286
2               3    Al-Imran             200
3               4     An-Nisa             176
4               5  Al-Ma'idah             120
..            ...         ...             ...
109           110     An-Nasr               3
110           111    Al-Masad               5
111           112   Al-Ikhlas               4
112           113    Al-Falaq               5
113           114      An-Nas               6

[114 rows x 3 columns]

In [28]:
# Trying scraping on a single ayah

options = Options()
options.headless = True
options.add_argument("--disable-gpu")
options.add_argument("--no-sandbox")
options.add_argument("--window-size=1920,1080")
prefs = {"profile.managed_default_content_settings.images": 2}
options.add_experimental_option("prefs", prefs)

url = 'https://www.altafsir.com/Tafasir.asp?tMadhNo=0&tTafsirNo=74&tSoraNo=1&tAyahNo=1&tDisplay=yes&UserProfile=0&LanguageId=2'

driver = webdriver.Chrome(options=options)
driver.get(url)

tafseer = driver.find_element(By.XPATH, '//*[@id="SearchResults"]/div/font/font')
tafseer.text

'In the Name of God the Compassionate the Merciful'

In [38]:
# Trying scraping on a single ayah

options = Options()
options.headless = True
options.add_argument("--disable-gpu")
options.add_argument("--no-sandbox")
options.add_argument("--window-size=1920,1080")

driver = webdriver.Chrome(options=options)
a = 1
b = 3
url = f'https://www.altafsir.com/Tafasir.asp?tMadhNo=0&tTafsirNo=74&tSoraNo={a}&tAyahNo={b}&tDisplay=yes&UserProfile=0&LanguageId=2'
driver.get(url)

tafseer = driver.find_element(By.XPATH, '//*[@id="SearchResults"]/div/font/font')
print(tafseer.text)

driver.quit()

The Compassionate the Merciful that is to say the One who possesses ‘mercy’ which means to want what is good for those who deserve it.

In [45]:
results = []
options = Options()
options.headless = True
options.add_argument("--disable-gpu")
options.add_argument("--no-sandbox")
options.add_argument("--window-size=1920,1080")
driver = webdriver.Chrome(options=options)
for _, surah in tqdm(quran.iterrows(), total=len(quran), desc="Surahs"):
    surah_number = surah["Surah Number"]
    num_ayat = surah["Number of Ayat"]

    for ayah_number in range(1, num_ayat + 1):
        url = f'https://www.altafsir.com/Tafasir.asp?tMadhNo=0&tTafsirNo=74&tSoraNo={surah_number}&tAyahNo={ayah_number}&tDisplay=yes&UserProfile=0&LanguageId=2'
        driver.get(url)

        tafseer = driver.find_element(By.XPATH, '//*[@id="SearchResults"]/div/font/font')
        results.append({
            "Surah Number": surah_number,
            "Ayah Number": ayah_number,
            "Text": tafseer.text
        })
driver.quit()

Surahs: 100%|██████████| 114/114 [2:54:59<00:00, 92.10s/it]

In [46]:
df_results = pd.DataFrame(results)
df_results.to_csv("tafseer_scraped.csv", index=False)

In [55]:
df_results

,Surah Number,Ayah Number,Text
0,1,1,In the Name of God the Compassionate the Merciful
1,1,2,In the Name of God the name of a thing is that...
2,1,3,The Compassionate the Merciful that is to say ...
3,1,4,Master of the Day of Judgement that is the day...
4,1,5,You alone we worship and You alone we ask for ...
...,...,...,...
6231,114,2,the King of mankind
6232,114,3,the God of mankind both maliki’l-nās and ilāhi...
6233,114,4,from the evil of the slinking whisperer Satan ...
6234,114,5,who whispers in the breasts of mankind in thei...
6235,114,6,of the jinn and mankind’ mina’l-jinnati wa’l-n...

### **Now I will try to scrape Tafseer al Jalaleen from this website**
`https://quran.com/`

`https://quran.com/{Surah_number}:{Ayah_number}/tafsirs/en-tafisr-ibn-kathir`

In [28]:
options = Options()
options.headless = True
options.add_argument("--disable-gpu")
options.add_argument("--no-sandbox")
options.add_argument("--window-size=1920,1080")
prefs = {"profile.managed_default_content_settings.images": 2}
options.add_experimental_option("prefs", prefs)

url = 'https://quran.com/1:7/tafsirs/en-tafisr-ibn-kathir'

In [32]:
wait = WebDriverWait(driver, 25)

tafseer_el = wait.until(
    EC.presence_of_element_located(
        (By.CSS_SELECTOR, 'div[class*="TafsirView"] div[class*="TafsirText_md"]')
    )
)

tafseer_text = tafseer_el.text.strip()
tafseer_text

'We mentioned the Hadith in which the servant proclaims,\nاهْدِنَا الصِّرَاطَ الْمُسْتَقِيمَ\n(Guide us to the straight way) and Allah says, "This is for My servant, and My servant shall acquire what he asks for." Allah\'s statement.\nصِرَاطَ الَّذِينَ أَنْعَمْتَ عَلَيْهِمْ\n(The way of those upon whom You have bestowed Your grace) defines the path. `Those upon whom Allah has bestowed His grace\' are those mentioned in Surat An-Nisa\' (chapter 4), when Allah said,\nوَمَن يُطِعِ اللَّهَ وَالرَّسُولَ فَأُوْلَـئِكَ مَعَ الَّذِينَ أَنْعَمَ اللَّهُ عَلَيْهِم مِّنَ النَّبِيِّينَ وَالصِّدِّيقِينَ وَالشُّهَدَآءِ وَالصَّـلِحِينَ وَحَسُنَ أُولَـئِكَ رَفِيقاً - ذلِكَ الْفَضْلُ مِنَ اللَّهِ وَكَفَى بِاللَّهِ عَلِيماً\n(And whoever obeys Allah and the Messenger (Muhammad ﷺ ), then they will be in the company of those on whom Allah has bestowed His grace, the Prophets, the Siddiqin (the truly faithful), the martyrs, and the righteous. And how excellent these companions are! Such is the bounty from Allah, and Allah is sufficient to know) (4:69-70).\nAllah\'s statement,\nغَيْرِ الْمَغْضُوبِ عَلَيْهِمْ وَلاَ الضَّآلِّينَ\n(Not (the way) of those who earned Your anger, nor of those who went astray) meaning guide us to the straight path, the path of those upon whom you have bestowed Your grace, that is, the people of guidance, sincerity and obedience to Allah and His Messengers. They are the people who adhere to Allah\'s commandments and refrain from committing what He has prohibited. But, help us to avoid the path of those whom Allah is angry with, whose intentions are corrupt, who know the truth, yet deviate from it. Also, help us avoid the path of those who were led astray, who lost the true knowledge and, as a result, are wandering in misguidance, unable to find the correct path. Allah asserted that the two paths He described here are both misguided when He repeated the negation `not\'. These two paths are the paths of the Christians and Jews, a fact that the believer should beware of so that he avoids them. The path of the believers is knowledge of the truth and abiding by it. In comparison, the Jews abandoned practicing the religion, while the Christians lost the true knowledge. This is why `anger\' descended upon the Jews, while being described as `led astray\' is more appropriate of the Christians. Those who know, but avoid implementing the truth, deserve the anger, unlike those who are ignorant. The Christians want to seek the true knowledge, but are unable to find it because they did not seek it from its proper resources.\nThis is why they were led astray. We should also mention that both the Christians and the Jews have earned the anger and are led astray, but the anger is one of the attributes more particular of the Jews. Allah said about the Jews,\nمَن لَّعَنَهُ اللَّهُ وَغَضِبَ عَلَيْهِ\n(Those (Jews) who incurred the curse of Allah and His wrath) (5:60).\nThe attribute that the Christians deserve most is that of being led astray, just as Allah said about them,\nقَدْ ضَلُّواْ مِن قَبْلُ وَأَضَلُّواْ كَثِيراً وَضَلُّواْ عَن سَوَآءِ السَّبِيلِ\n(Who went astray before and who misled many, and strayed (themselves) from the right path) (5:77).\nThere are several Hadiths and reports from the Salaf on this subject. Imam Ahmad recorded that `Adi bin Hatim said, "The horsemen of the Messenger of Allah ﷺ seized my paternal aunt and some other people. When they brought them to the Messenger of Allah ﷺ , they were made to stand in line before him. My aunt said, `O Messenger of Allah ﷺ ! The supporter is far away, the offspring have stopped coming and I am an old woman, unable to serve. Grant me your favor, may Allah grant you His favor.\' He said, `Who is your supporter\' She said, `Adi bin Hatim.\' He said, `The one who ran away from Allah and His Messenger\' She said, `So, the Prophet ﷺ freed me.\' When the Prophet ﷺ came back, there was a man next to him, I think that he was `Ali, who said to her, `Ask him for a means of transportation.\' She asked the Prophet ﷺ, and he ordered that she be given an animal.\n" `Adi then said, "Later on, she came to me and said, `He (Muhammad ﷺ ) has done a favor that your father (who was a generous man) would never have done. So and-so person came to him and he granted him his favor, and so-and-so came to him and he granted him his favor.\' So I went to the Prophet ﷺ and found that some women and children were gathering with him, so close that I knew that he was not a king like Kisra (King of Persia) or Caesar. He said, `O `Adi! What made you run away, so that La ilaha illallah is not proclaimed Is there a deity worthy of worship except Allah What made you run away, so that Allahu Akbar (Allah is the Greater) is not proclaimed Is there anything Greater than Allah\' I proclaimed my Islam and I saw his face radiate with pleasure and he said:\n«إِنَّ الْمَغْضُوبَ عَلَيْهِمُ الْيَهُودُ وَ إِنَّ الضَّالِينَ النَّصَارَى»\n(Those who have earned the anger are the Jews and those who are led astray are the Christians.)"\nThis Hadith was also collected by At-Tirmidhi who said that it is Hasan Gharib.\nAlso, when Zayd bin `Amr bin Nufayl went with some of his friends - before Islam - to Ash-Sham seeking the true religion, the Jews said to him, "You will not become a Jew unless you carry a share of the anger of Allah that we have earned." He said, "I am seeking to escape Allah\'s anger." Also, the Christians said to him, "If you become one of us you will carry a share in Allah\'s discontent." He said, "I cannot bear it." So he remained in his pure nature and avoided worshipping the idols and the polytheistic practices. He became neither a Jew, nor Christian. As for his companions, they became Christians because they found it more pure than Judaism. Waraqah bin Nawfal was among these people until Allah guided him by the hand of His Prophet, when he was sent as Prophet, and Waraqah believed in the revelation that was sent to the Prophet ﷺ may Allah be pleased with him.\nThe Summary of Al-Fatihah\nThe honorable Surah Al-Fatihah contains seven Ayat including the praise and thanks of Allah, glorifying Him and praising Him by mentioning His most Beautiful Names and most high Attributes. It also mentions the Hereafter, which is the Day of Resurrection, and directs Allah\'s servants to ask of Him, invoking Him and declaring that all power and strength comes from Him. It also calls to the sincerity of the worship of Allah alone, singling Him out in His divinity, believing in His perfection, being free from the need of any partners, having no rivals nor equals. Al-Fatihah directs the believers to invoke Allah to guide them to the straight path, which is the true religion, and to help them remain on that path in this life, and to pass over the actual Sirat (bridge over hell that everyone must pass over) on the Day of Judgment. On that Day, the believers will be directed to the gardens of comfort in the company of the Prophets, the truthful ones, the martyrs and the righteous. Al-Fatihah also encourages performing good deeds, so that the believers will be in the company of the good-doers on the Day of Resurrection. The Surah also warns against following the paths of misguidance, so that one does not end up being gathered with those who indulge in sin, on the Day of Resurrection, including those who have earned the anger and those who were led astray.\nThe Bounties are because of Allah, not the Deviations\nAllah said,\nصِرَاطَ الَّذِينَ أَنْعَمْتَ عَلَيْهِمْ\n(The way of those upon whom you have bestowed Your grace), when He mentioned His favor. On mentioning anger, Allah said,\nغَيْرِ الْمَغْضُوبِ عَلَيْهِمْ\n(Not (that) of those who earned Your anger), without mentioning the subject, although it is He Who has sent down the anger on them, just as Allah stated in another Ayah,\nأَلَمْ تَرَ إِلَى الَّذِينَ تَوَلَّوْاْ قَوْماً غَضِبَ اللَّهُ عَلَيْهِم\n(Have you (O Muhammad ) not seen those (hypocrites) who take as friends a people upon whom is the wrath of Allah (i.e. Jews)) (58:14).\nAlso, Allah relates the misguidance of those who indulged in it, although they were justly misguided according to Allah\'s appointed destiny. For instance, Allah said,\nمَن يَهْدِ اللَّهُ فَهُوَ الْمُهْتَدِ وَمَن يُضْلِلْ فَلَن تَجِدَ لَهُ وَلِيًّا مُّرْشِدًا\n(He whom Allah guides, he is the rightly-guided; but he whom He sends astray, for him you will find no Wali (guiding friend) to lead him (to the right path)) (18:17)\nand,\nمَن يُضْلِلِ اللَّهُ فَلاَ هَادِيَ لَهُ وَيَذَرُهُمْ فِى طُغْيَـنِهِمْ يَعْمَهُونَ\n(Whomsoever Allah sends astray, none can guide him; and He lets them wander blindly in their transgression) (7:186).\nThese and several other Ayat testify to the fact that Allah alone is the One Who guides and misguides, contrary to the belief of the Qadariyyah sect, who claimed that the servants choose and create their own destiny. They rely on some unclear Ayat avoiding what is clear and contradicts their desires. Theirs, is the method of the people who follow their lust, desire and wickedness. An authentic Hadith narrated,\n«إِذَا رَأَيْتُمُ الَّذِينَ يَتَّبِعُونَ مَا تَشَابَهَ مِنْهُ فَأُولئِكَ الَّذِينَ سَمَّى اللهُ فَاحْذَرُوهُمْ»\n(When you see those who follow what is not so clear in it (the Qur\'an), then they are those whom Allah has mentioned (refer to 3:7). Hence, avoid them.)\nThe Prophet ﷺ was referring to Allah\'s statement,\nفَأَمَّا الَّذِينَ فى قُلُوبِهِمْ زَيْغٌ فَيَتَّبِعُونَ مَا تَشَـبَهَ مِنْهُ ابْتِغَآءَ الْفِتْنَةِ وَابْتِغَآءَ تَأْوِيلِهِ\n(So as for those in whose hearts there is a deviation (from the truth) they follow that which is not entirely clear thereof, seeking Al-Fitnah (polytheism and trials), and seeking for its hidden meanings)(3:7).\nVerily, no innovator in the religion could ever rely on any authentic evidence in the Qur\'an that testifies to his innovation. The Qur\'an came to distinguish between truth and falsehood, and guidance and misguidance. The Qur\'an does not contain any discrepancies or contradictions, because it is a revelation from the Most Wise, Worthy of all praise.\nSaying Amin\nIt is recommended to say Amin after finishing the recitation of Al-Fatihah. Amin means, "O Allah! Accept our invocation." The evidence that saying Amin is recommended is contained in what Imams Ahmad, Abu Dawud and At-Tirmidhi recorded, that Wa\'il bin Hujr said, "I heard the Messenger of Allah ﷺ recite,\nغَيْرِ الْمَغْضُوبِ عَلَيْهِمْ وَلاَ الضَّآلِّينَ\n(Not (that) of those who earned Your anger, nor of those who went astray), and he said `Amin\' extending it with his voice."\nAbu Dawud\'s narration added, "Raising his voice with it." At-Tirmidhi then commented that this Hadith is Hasan and was also narrated from `Ali and Ibn Mas`ud. Also, Abu Hurayrah narrated that whenever the Messenger of Allah ﷺ would recite,\nغَيْرِ الْمَغْضُوبِ عَلَيْهِمْ وَلاَ الضَّآلِّينَ\n(Not (the way) of those who earned Your anger, nor of those who went astray), He would say Amin until those who were behind him in the first line could hear him.\nAbu Dawud and Ibn Majah recorded this Hadith with the addition, "Then the Masjid would shake because of (those behind the Prophet ﷺ) reciting Amin." Also, Ad-Daraqutni recorded this Hadith and commented that it is Hasan.\nFurther, Bilal narrated that he said, "O Messenger of Allah ﷺ ! Do not finish saying Amin before I can join you." This was recorded by Abu Dawud.\nIn addition, Abu Nasr Al-Qushayri narrated that Al-Hasan and Ja`far As-Sadiq stressed the `m\' in Amin.\nSaying Amin is recommended for those who are not praying (when reciting Al-Fatihah) and is strongly recommended for those who are praying, whether alone or behind the Imam. The Two Sahihs recorded that the Messenger of Allah ﷺ said,\n«إِذَا أَمَّنَ الْإِمَامُ فَأَمِّنُوا، فَإِنَّهُ مَنْ وَافَقَ تَأْمِينُهُ تَأْمِينَ الْمَلَائِكَةِ غُفِرَ لَهُ مَا تَقَدَّمَ مِنْ ذَنْبِهِ»\n(When the Imam says, \' Amin\', then say, \'Amin\', because whoever says, Amin\' with the angels, his previous sins will be forgiven.)\nMuslim recorded that the Messenger of Allah ﷺ said,\n«إِذَا قَالَ أَحَدُكُمْ فِي الصَّلَاةِ: آمِينَ، وَالْمَلَائِكَةُ فِي السَّمَاءِ: آمِينَ، فَوَافَقَتْ إِحْدَاهُمَا الْأُخْرَى غُفِرَ لَهُ مَا تَقَدَّمَ مِنْ ذَنْبِهِ»\n(When any of you says in the prayer, \'Amin ` and the angels in heaven say, `Amin\', in unison, his previous sins will be forgiven.)\nIt was said that the Hadith talks about both the angels and the Muslims saying Amin at the same time. The Hadith also refers to when the Amins said by the angels and the Muslims are equally sincere (thus bringing about forgiveness).\nFurther, it is recorded in Sahih Muslim that Abu Musa related to the Prophet ﷺ that he said,\n«إِذَا قَالَ يَعنِي الْإِمَامَ : وَلَا الضَّالِّينَ، فَقُولُوا: آمِينَ، يُجِبْكُمُ اللهُ»\n(When the Imam says, `Walad-dallin\', say, `Amin\' and Allah will answer your invocation.)\nIn addition, At-Tirmidhi said that `Amin\' means, "Do not disappoint our hope", while the majority of scholars said that it means. "Answer our invocation."\nAlso, in his Musnad, Imam Ahmad recorded that `A\'ishah said that when the Jews were mentioned to him, the Messenger of Allah ﷺ said,\n«إِنَّهُم لَنْ يَحْسُدُونَا عَلَى شَيْءٍ كَمَا يَحْسُدُونَا عَلَى الْجُمُعَةِ الَّتِي هَدَانَا اللهُ لَهَا وَضَلُّوا عَنْهَا، وَعَلَى الْقِبْلَةِ الَّتِي هَدَانَا اللهُ لَهَا وَضَلُّوا عَنْهَا وَعَلَى قَوْلِنَا خَلْفَ الْإِمَامِ: آمِينَ»\n(They will not envy us for anything more than they envy us for Friday which we have been guided to, while they were led astray from it, and for the Qiblah which we were guided to, while they were led astray from it, and for our saying `Amin\' behind the Imam.)\nAlso, Ibn Majah recorded this Hadith with the wording,\n«مَا حَسَدَتْكُمُ الْيَهُودُ عَلَى شَيْءٍ مَا حَسَدَتْكُمْ عَلَى السَّلَامِ وَالتَّأْمِينِ»\n(The Jews have never envied you more than for your saying the Salam (Islamic greeting) and for saying Amin.) rgiveness). veneooA ? Further, it is recorded in Sahih Muslim that Abu Musa related to the Prophet ﷺ that he said,\n«إِذَا قَالَ يَعنِي الْإِمَامَ : وَلَا الضَّالِّينَ، فَقُولُوا: آمِينَ، يُجِبْكُمُ اللهُ»\n(When the Imam says, `Walad-dallin\', say, `Amin\' and Allah will answer your invocation.)\nIn addition, At-Tirmidhi said that `Amin\' means, "Do not disappoint our hope", while the majority of scholars said that it means. "Answer our invocation."\nAlso, in his Musnad, Imam Ahmad recorded that `A\'ishah said that when the Jews were mentioned to him, the Messenger of Allah ﷺ said,\n«إِنَّهُم لَنْ يَحْسُدُونَا عَلَى شَيْءٍ كَمَا يَحْسُدُونَا عَلَى الْجُمُعَةِ الَّتِي هَدَانَا اللهُ لَهَا وَضَلُّوا عَنْهَا، وَعَلَى الْقِبْلَةِ الَّتِي هَدَانَا اللهُ لَهَا وَضَلُّوا عَنْهَا وَعَلَى قَوْلِنَا خَلْفَ الْإِمَامِ: آمِينَ»\n(They will not envy us for anything more than they envy us for Friday which we have been guided to, while they were led astray from it, and for the Qiblah which we were guided to, while they were led astray from it, and for our saying `Amin\' behind the Imam.)\nAlso, Ibn Majah recorded this Hadith with the wording,\n«مَا حَسَدَتْكُمُ الْيَهُودُ عَلَى شَيْءٍ مَا حَسَدَتْكُمْ عَلَى السَّلَامِ وَالتَّأْمِينِ»\n(The Jews have never envied you more than for your saying the Salam (Islamic greeting) and for saying Amin.)'

In [27]:
driver = webdriver.Chrome(options=options)
driver.get(url)

tafseer = driver.find_element(By.XPATH, '//*[@id="__next"]/div/div[3]/div/div[3]/div')
tafseer.text

'صراط الذين انعمت عليهم غير المغضوب عليهم ولا الضالين ٧\nﭫ\nﭬ\nﭭ\nﭮ\nﭯ\nﭰ\nﭱ\nﭲ\nﭳ\nﭴ\n3\nWe mentioned the Hadith in which the servant proclaims,\nاهْدِنَا الصِّرَاطَ الْمُسْتَقِيمَ\n(Guide us to the straight way) and Allah says, "This is for My servant, and My servant shall acquire what he asks for." Allah\'s statement.\nصِرَاطَ الَّذِينَ أَنْعَمْتَ عَلَيْهِمْ\n(The way of those upon whom You have bestowed Your grace) defines the path. `Those upon whom Allah has bestowed His grace\' are those mentioned in Surat An-Nisa\' (chapter 4), when Allah said,\nوَمَن يُطِعِ اللَّهَ وَالرَّسُولَ فَأُوْلَـئِكَ مَعَ الَّذِينَ أَنْعَمَ اللَّهُ عَلَيْهِم مِّنَ النَّبِيِّينَ وَالصِّدِّيقِينَ وَالشُّهَدَآءِ وَالصَّـلِحِينَ وَحَسُنَ أُولَـئِكَ رَفِيقاً - ذلِكَ الْفَضْلُ مِنَ اللَّهِ وَكَفَى بِاللَّهِ عَلِيماً\n(And whoever obeys Allah and the Messenger (Muhammad ﷺ ), then they will be in the company of those on whom Allah has bestowed His grace, the Prophets, the Siddiqin (the truly faithful), the martyrs, and the righteous. And how excellent these companions are! Such is the bounty from Allah, and Allah is sufficient to know) (4:69-70).\nAllah\'s statement,\nغَيْرِ الْمَغْضُوبِ عَلَيْهِمْ وَلاَ الضَّآلِّينَ\n(Not (the way) of those who earned Your anger, nor of those who went astray) meaning guide us to the straight path, the path of those upon whom you have bestowed Your grace, that is, the people of guidance, sincerity and obedience to Allah and His Messengers. They are the people who adhere to Allah\'s commandments and refrain from committing what He has prohibited. But, help us to avoid the path of those whom Allah is angry with, whose intentions are corrupt, who know the truth, yet deviate from it. Also, help us avoid the path of those who were led astray, who lost the true knowledge and, as a result, are wandering in misguidance, unable to find the correct path. Allah asserted that the two paths He described here are both misguided when He repeated the negation `not\'. These two paths are the paths of the Christians and Jews, a fact that the believer should beware of so that he avoids them. The path of the believers is knowledge of the truth and abiding by it. In comparison, the Jews abandoned practicing the religion, while the Christians lost the true knowledge. This is why `anger\' descended upon the Jews, while being described as `led astray\' is more appropriate of the Christians. Those who know, but avoid implementing the truth, deserve the anger, unlike those who are ignorant. The Christians want to seek the true knowledge, but are unable to find it because they did not seek it from its proper resources.\nThis is why they were led astray. We should also mention that both the Christians and the Jews have earned the anger and are led astray, but the anger is one of the attributes more particular of the Jews. Allah said about the Jews,\nمَن لَّعَنَهُ اللَّهُ وَغَضِبَ عَلَيْهِ\n(Those (Jews) who incurred the curse of Allah and His wrath) (5:60).\nThe attribute that the Christians deserve most is that of being led astray, just as Allah said about them,\nقَدْ ضَلُّواْ مِن قَبْلُ وَأَضَلُّواْ كَثِيراً وَضَلُّواْ عَن سَوَآءِ السَّبِيلِ\n(Who went astray before and who misled many, and strayed (themselves) from the right path) (5:77).\nThere are several Hadiths and reports from the Salaf on this subject. Imam Ahmad recorded that `Adi bin Hatim said, "The horsemen of the Messenger of Allah ﷺ seized my paternal aunt and some other people. When they brought them to the Messenger of Allah ﷺ , they were made to stand in line before him. My aunt said, `O Messenger of Allah ﷺ ! The supporter is far away, the offspring have stopped coming and I am an old woman, unable to serve. Grant me your favor, may Allah grant you His favor.\' He said, `Who is your supporter\' She said, `Adi bin Hatim.\' He said, `The one who ran away from Allah and His Messenger\' She said, `So, the Prophet ﷺ freed me.\' When the Prophet ﷺ came back, there was a man next to him, I think that he was `Ali, who said to her, `Ask him for a means of transportation.\' She asked the Prophet ﷺ, and he ordered that she be given an animal.\n" `Adi then said, "Later on, she came to me and said, `He (Muhammad ﷺ ) has done a favor that your father (who was a generous man) would never have done. So and-so person came to him and he granted him his favor, and so-and-so came to him and he granted him his favor.\' So I went to the Prophet ﷺ and found that some women and children were gathering with him, so close that I knew that he was not a king like Kisra (King of Persia) or Caesar. He said, `O `Adi! What made you run away, so that La ilaha illallah is not proclaimed Is there a deity worthy of worship except Allah What made you run away, so that Allahu Akbar (Allah is the Greater) is not proclaimed Is there anything Greater than Allah\' I proclaimed my Islam and I saw his face radiate with pleasure and he said:\n«إِنَّ الْمَغْضُوبَ عَلَيْهِمُ الْيَهُودُ وَ إِنَّ الضَّالِينَ النَّصَارَى»\n(Those who have earned the anger are the Jews and those who are led astray are the Christians.)"\nThis Hadith was also collected by At-Tirmidhi who said that it is Hasan Gharib.\nAlso, when Zayd bin `Amr bin Nufayl went with some of his friends - before Islam - to Ash-Sham seeking the true religion, the Jews said to him, "You will not become a Jew unless you carry a share of the anger of Allah that we have earned." He said, "I am seeking to escape Allah\'s anger." Also, the Christians said to him, "If you become one of us you will carry a share in Allah\'s discontent." He said, "I cannot bear it." So he remained in his pure nature and avoided worshipping the idols and the polytheistic practices. He became neither a Jew, nor Christian. As for his companions, they became Christians because they found it more pure than Judaism. Waraqah bin Nawfal was among these people until Allah guided him by the hand of His Prophet, when he was sent as Prophet, and Waraqah believed in the revelation that was sent to the Prophet ﷺ may Allah be pleased with him.\nThe Summary of Al-Fatihah\nThe honorable Surah Al-Fatihah contains seven Ayat including the praise and thanks of Allah, glorifying Him and praising Him by mentioning His most Beautiful Names and most high Attributes. It also mentions the Hereafter, which is the Day of Resurrection, and directs Allah\'s servants to ask of Him, invoking Him and declaring that all power and strength comes from Him. It also calls to the sincerity of the worship of Allah alone, singling Him out in His divinity, believing in His perfection, being free from the need of any partners, having no rivals nor equals. Al-Fatihah directs the believers to invoke Allah to guide them to the straight path, which is the true religion, and to help them remain on that path in this life, and to pass over the actual Sirat (bridge over hell that everyone must pass over) on the Day of Judgment. On that Day, the believers will be directed to the gardens of comfort in the company of the Prophets, the truthful ones, the martyrs and the righteous. Al-Fatihah also encourages performing good deeds, so that the believers will be in the company of the good-doers on the Day of Resurrection. The Surah also warns against following the paths of misguidance, so that one does not end up being gathered with those who indulge in sin, on the Day of Resurrection, including those who have earned the anger and those who were led astray.\nThe Bounties are because of Allah, not the Deviations\nAllah said,\nصِرَاطَ الَّذِينَ أَنْعَمْتَ عَلَيْهِمْ\n(The way of those upon whom you have bestowed Your grace), when He mentioned His favor. On mentioning anger, Allah said,\nغَيْرِ الْمَغْضُوبِ عَلَيْهِمْ\n(Not (that) of those who earned Your anger), without mentioning the subject, although it is He Who has sent down the anger on them, just as Allah stated in another Ayah,\nأَلَمْ تَرَ إِلَى الَّذِينَ تَوَلَّوْاْ قَوْماً غَضِبَ اللَّهُ عَلَيْهِم\n(Have you (O Muhammad ) not seen those (hypocrites) who take as friends a people upon whom is the wrath of Allah (i.e. Jews)) (58:14).\nAlso, Allah relates the misguidance of those who indulged in it, although they were justly misguided according to Allah\'s appointed destiny. For instance, Allah said,\nمَن يَهْدِ اللَّهُ فَهُوَ الْمُهْتَدِ وَمَن يُضْلِلْ فَلَن تَجِدَ لَهُ وَلِيًّا مُّرْشِدًا\n(He whom Allah guides, he is the rightly-guided; but he whom He sends astray, for him you will find no Wali (guiding friend) to lead him (to the right path)) (18:17)\nand,\nمَن يُضْلِلِ اللَّهُ فَلاَ هَادِيَ لَهُ وَيَذَرُهُمْ فِى طُغْيَـنِهِمْ يَعْمَهُونَ\n(Whomsoever Allah sends astray, none can guide him; and He lets them wander blindly in their transgression) (7:186).\nThese and several other Ayat testify to the fact that Allah alone is the One Who guides and misguides, contrary to the belief of the Qadariyyah sect, who claimed that the servants choose and create their own destiny. They rely on some unclear Ayat avoiding what is clear and contradicts their desires. Theirs, is the method of the people who follow their lust, desire and wickedness. An authentic Hadith narrated,\n«إِذَا رَأَيْتُمُ الَّذِينَ يَتَّبِعُونَ مَا تَشَابَهَ مِنْهُ فَأُولئِكَ الَّذِينَ سَمَّى اللهُ فَاحْذَرُوهُمْ»\n(When you see those who follow what is not so clear in it (the Qur\'an), then they are those whom Allah has mentioned (refer to 3:7). Hence, avoid them.)\nThe Prophet ﷺ was referring to Allah\'s statement,\nفَأَمَّا الَّذِينَ فى قُلُوبِهِمْ زَيْغٌ فَيَتَّبِعُونَ مَا تَشَـبَهَ مِنْهُ ابْتِغَآءَ الْفِتْنَةِ وَابْتِغَآءَ تَأْوِيلِهِ\n(So as for those in whose hearts there is a deviation (from the truth) they follow that which is not entirely clear thereof, seeking Al-Fitnah (polytheism and trials), and seeking for its hidden meanings)(3:7).\nVerily, no innovator in the religion could ever rely on any authentic evidence in the Qur\'an that testifies to his innovation. The Qur\'an came to distinguish between truth and falsehood, and guidance and misguidance. The Qur\'an does not contain any discrepancies or contradictions, because it is a revelation from the Most Wise, Worthy of all praise.\nSaying Amin\nIt is recommended to say Amin after finishing the recitation of Al-Fatihah. Amin means, "O Allah! Accept our invocation." The evidence that saying Amin is recommended is contained in what Imams Ahmad, Abu Dawud and At-Tirmidhi recorded, that Wa\'il bin Hujr said, "I heard the Messenger of Allah ﷺ recite,\nغَيْرِ الْمَغْضُوبِ عَلَيْهِمْ وَلاَ الضَّآلِّينَ\n(Not (that) of those who earned Your anger, nor of those who went astray), and he said `Amin\' extending it with his voice."\nAbu Dawud\'s narration added, "Raising his voice with it." At-Tirmidhi then commented that this Hadith is Hasan and was also narrated from `Ali and Ibn Mas`ud. Also, Abu Hurayrah narrated that whenever the Messenger of Allah ﷺ would recite,\nغَيْرِ الْمَغْضُوبِ عَلَيْهِمْ وَلاَ الضَّآلِّينَ\n(Not (the way) of those who earned Your anger, nor of those who went astray), He would say Amin until those who were behind him in the first line could hear him.\nAbu Dawud and Ibn Majah recorded this Hadith with the addition, "Then the Masjid would shake because of (those behind the Prophet ﷺ) reciting Amin." Also, Ad-Daraqutni recorded this Hadith and commented that it is Hasan.\nFurther, Bilal narrated that he said, "O Messenger of Allah ﷺ ! Do not finish saying Amin before I can join you." This was recorded by Abu Dawud.\nIn addition, Abu Nasr Al-Qushayri narrated that Al-Hasan and Ja`far As-Sadiq stressed the `m\' in Amin.\nSaying Amin is recommended for those who are not praying (when reciting Al-Fatihah) and is strongly recommended for those who are praying, whether alone or behind the Imam. The Two Sahihs recorded that the Messenger of Allah ﷺ said,\n«إِذَا أَمَّنَ الْإِمَامُ فَأَمِّنُوا، فَإِنَّهُ مَنْ وَافَقَ تَأْمِينُهُ تَأْمِينَ الْمَلَائِكَةِ غُفِرَ لَهُ مَا تَقَدَّمَ مِنْ ذَنْبِهِ»\n(When the Imam says, \' Amin\', then say, \'Amin\', because whoever says, Amin\' with the angels, his previous sins will be forgiven.)\nMuslim recorded that the Messenger of Allah ﷺ said,\n«إِذَا قَالَ أَحَدُكُمْ فِي الصَّلَاةِ: آمِينَ، وَالْمَلَائِكَةُ فِي السَّمَاءِ: آمِينَ، فَوَافَقَتْ إِحْدَاهُمَا الْأُخْرَى غُفِرَ لَهُ مَا تَقَدَّمَ مِنْ ذَنْبِهِ»\n(When any of you says in the prayer, \'Amin ` and the angels in heaven say, `Amin\', in unison, his previous sins will be forgiven.)\nIt was said that the Hadith talks about both the angels and the Muslims saying Amin at the same time. The Hadith also refers to when the Amins said by the angels and the Muslims are equally sincere (thus bringing about forgiveness).\nFurther, it is recorded in Sahih Muslim that Abu Musa related to the Prophet ﷺ that he said,\n«إِذَا قَالَ يَعنِي الْإِمَامَ : وَلَا الضَّالِّينَ، فَقُولُوا: آمِينَ، يُجِبْكُمُ اللهُ»\n(When the Imam says, `Walad-dallin\', say, `Amin\' and Allah will answer your invocation.)\nIn addition, At-Tirmidhi said that `Amin\' means, "Do not disappoint our hope", while the majority of scholars said that it means. "Answer our invocation."\nAlso, in his Musnad, Imam Ahmad recorded that `A\'ishah said that when the Jews were mentioned to him, the Messenger of Allah ﷺ said,\n«إِنَّهُم لَنْ يَحْسُدُونَا عَلَى شَيْءٍ كَمَا يَحْسُدُونَا عَلَى الْجُمُعَةِ الَّتِي هَدَانَا اللهُ لَهَا وَضَلُّوا عَنْهَا، وَعَلَى الْقِبْلَةِ الَّتِي هَدَانَا اللهُ لَهَا وَضَلُّوا عَنْهَا وَعَلَى قَوْلِنَا خَلْفَ الْإِمَامِ: آمِينَ»\n(They will not envy us for anything more than they envy us for Friday which we have been guided to, while they were led astray from it, and for the Qiblah which we were guided to, while they were led astray from it, and for our saying `Amin\' behind the Imam.)\nAlso, Ibn Majah recorded this Hadith with the wording,\n«مَا حَسَدَتْكُمُ الْيَهُودُ عَلَى شَيْءٍ مَا حَسَدَتْكُمْ عَلَى السَّلَامِ وَالتَّأْمِينِ»\n(The Jews have never envied you more than for your saying the Salam (Islamic greeting) and for saying Amin.) rgiveness). veneooA ? Further, it is recorded in Sahih Muslim that Abu Musa related to the Prophet ﷺ that he said,\n«إِذَا قَالَ يَعنِي الْإِمَامَ : وَلَا الضَّالِّينَ، فَقُولُوا: آمِينَ، يُجِبْكُمُ اللهُ»\n(When the Imam says, `Walad-dallin\', say, `Amin\' and Allah will answer your invocation.)\nIn addition, At-Tirmidhi said that `Amin\' means, "Do not disappoint our hope", while the majority of scholars said that it means. "Answer our invocation."\nAlso, in his Musnad, Imam Ahmad recorded that `A\'ishah said that when the Jews were mentioned to him, the Messenger of Allah ﷺ said,\n«إِنَّهُم لَنْ يَحْسُدُونَا عَلَى شَيْءٍ كَمَا يَحْسُدُونَا عَلَى الْجُمُعَةِ الَّتِي هَدَانَا اللهُ لَهَا وَضَلُّوا عَنْهَا، وَعَلَى الْقِبْلَةِ الَّتِي هَدَانَا اللهُ لَهَا وَضَلُّوا عَنْهَا وَعَلَى قَوْلِنَا خَلْفَ الْإِمَامِ: آمِينَ»\n(They will not envy us for anything more than they envy us for Friday which we have been guided to, while they were led astray from it, and for the Qiblah which we were guided to, while they were led astray from it, and for our saying `Amin\' behind the Imam.)\nAlso, Ibn Majah recorded this Hadith with the wording,\n«مَا حَسَدَتْكُمُ الْيَهُودُ عَلَى شَيْءٍ مَا حَسَدَتْكُمْ عَلَى السَّلَامِ وَالتَّأْمِينِ»\n(The Jews have never envied you more than for your saying the Salam (Islamic greeting) and for saying Amin.)\nPrevious Ayah'

In [7]:
folder_name = "ayat"
os.makedirs(folder_name, exist_ok=True)

options = Options()
options.headless = True
options.add_argument("--disable-gpu")
options.add_argument("--no-sandbox")
options.add_argument("--window-size=1920,1080")
driver = webdriver.Chrome(options=options)
for _, surah in tqdm(quran.iterrows() , total=len(quran), desc="Surahs"):
    surah_number = surah["Surah Number"]
    surah_number = surah["Surah Number"]
    num_ayat = surah["Number of Ayat"]

    for ayah_number in range(1, num_ayat + 1):
        url = f'https://quran.com/{surah_number}:{ayah_number}/tafsirs/en-tafisr-ibn-kathir'
        driver.get(url)

        wait = WebDriverWait(driver, 25)

        tafseer_el = wait.until(
            EC.presence_of_element_located(
                (By.CSS_SELECTOR, 'div[class*="TafsirView"] div[class*="TafsirText_md"]')
            )
        )

        tafseer_text = tafseer_el.text.strip()

        res = {
            "Surah Number": surah_number,
            "Ayah Number": ayah_number,
            "Text": tafseer_text
        }

        time.sleep(1)
        filename = f"{surah_number}_{ayah_number}.txt"
        filepath = os.path.join(folder_name, filename)

        with open(filepath, "w", encoding="utf-8") as f:
            json.dump(res, f, ensure_ascii=False, indent=2)
driver.quit()

Surahs: 100%|██████████| 114/114 [16:06<00:00,  8.48s/it]

In [23]:
folder_path = "ayat"
all_data = []

for filename in os.listdir(folder_path):
    if filename.endswith(".txt"):
        file_path = os.path.join(folder_path, filename)
        with open(file_path, "r", encoding="utf-8") as f:
            try:
                data = json.load(f)
                all_data.append(data)
            except json.JSONDecodeError:
                print(f"Skipping {filename}, not valid JSON")

df = pd.DataFrame(all_data)
df = df.sort_values(["Surah Number", "Ayah Number"])

df.to_csv("combined_tafseer.csv", index=False, encoding="utf-8")
print("Saved combined_tafseer.csv successfully!")

Saved combined_tafseer.csv successfully!

In [24]:
df

,Surah Number,Ayah Number,Text
1074,1,1,Introduction to Fatihah\nWhich was revealed in...
1075,1,2,The Meaning of Al-Hamd\nAbu Ja`far bin Jarir s...
1076,1,3,"Allah said next,\nالرَّحْمَـنِ الرَّحِيمِ\n(Ar..."
1077,1,4,Indicating Sovereignty on the Day of Judgment\...
1078,1,5,The Linguistic and Religious Meaning of `Ibada...
...,...,...,...
194,114,2,Which was revealed in Makkah\nبِسْمِ اللَّهِ ا...
195,114,3,Which was revealed in Makkah\nبِسْمِ اللَّهِ ا...
196,114,4,Which was revealed in Makkah\nبِسْمِ اللَّهِ ا...
197,114,5,Which was revealed in Makkah\nبِسْمِ اللَّهِ ا...
198,114,6,Which was revealed in Makkah\nبِسْمِ اللَّهِ ا...